[package]
name = "battery-health-keeper"
version = "0.0.1"
edition = "2021"
description = "A simple battery health keeper for Linux"

[dependencies]
eframe = { version = "0.36.1", default-features = false, features = ["default_fonts", "glow", "wayland", "x11"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
image = { version = "0.25", default-features = false, features = ["png"] }

[profile.release]
opt-level = 2
lto = true
